-- 1. STERGERA PROCEDURILOR STOCATE
DROP PROCEDURE IF EXISTS sp_GetCategorii;
DROP PROCEDURE IF EXISTS sp_InsertCategorie;
DROP PROCEDURE IF EXISTS sp_LoginUtilizator;
DROP PROCEDURE IF EXISTS sp_InsertUtilizator;
DROP PROCEDURE IF EXISTS sp_GetPreparate;
DROP PROCEDURE IF EXISTS sp_UpdateStocPreparat;
DROP PROCEDURE IF EXISTS sp_SetPreparatIndisponibil;
DROP PROCEDURE IF EXISTS sp_GetComenziClient;
DROP PROCEDURE IF EXISTS sp_UpdateStareComanda;
DROP PROCEDURE IF EXISTS sp_InsertComanda;
GO

-- 2. STERGEREA TABELELOR (Ordinea contează enorm aici!)
DROP TABLE IF EXISTS DetaliiComanda;
DROP TABLE IF EXISTS Comenzi;
DROP TABLE IF EXISTS MeniuriPreparate;
DROP TABLE IF EXISTS Meniuri;
DROP TABLE IF EXISTS PreparateAlergeni;
DROP TABLE IF EXISTS Alergeni;
DROP TABLE IF EXISTS FotografiiPreparate;
DROP TABLE IF EXISTS Preparate;
DROP TABLE IF EXISTS Utilizatori;
DROP TABLE IF EXISTS Categorii;
GO